### PR TITLE
Allow build-level overrides for Campfire subdomain and token

### PR DESCRIPTION
**Pull request by jsl**
We run a consultancy, so we have a Jenkins server that needs to notify Campfire rooms for multiple organizations. This change allows the user to customize the API token and subdomain on a per-project basis to override global defaults.

### CODE REVIEW

**Comment by jsl** [comment]
This is causing a problem for us locally, so I think there is a bug somewhere. Closing while I investigate.

**Comment by jsl** [comment]
This is working for us now after allowing the Campfire class to be serialized, so re-opening.

**Comment by mmrwoods** [comment]
Hey,

Thanks for this, looks good to me. I've no jenkins instance to test on at the moment though, so it would be nice if someone else could test it before it's merged.

The only thing I'm unsure of is the use of a "cf" prefix in the request parameters. I vaguely recall that this isn't necessary, that the form elements get some kind of namespacing automagically, but it's a while since I've looked at jenkins, and, as mentioned, I've no way of testing at the moment. Could you check it and remove the prefix if it isn't necessary?

**Comment by mmrwoods** [comment]
Nice :-)

**Comment by jsl** [comment]
Thanks @thickpaddy. I did some research and you're right, it seems the fields are automagically namespaced:

http://wiki.hudson-ci.org/display/HUDSON/Structured+Form+Submission

I did remove the 'cf' prefix, but you'll see that I changed it to 'campfire' instead. This is to match the field names used in the global configuration form. 

At this point the code that pulls parameters from the request in the methods for processing the incoming fields in the global and per-project methods is almost identical, so it made sense to me to homogenize the field names for consistency and so that the common code may be extracted more easily in the future. Let me know if you have another preference for these field names and I'll test and push it.

I'll continue to test this plugin on our Jenkins server that is now posting to campfire rooms under three organizations, and I don't mind if you want to hold on this PR until someone else volunteers to test the plugin on another server - it makes sense to me as well to make sure this is ready before merging to master.

**Pull request merged**
